---
name: Test
on:
  push:
    paths-ignore:
      - .clang-format
      - .clojure
      - .editorconfig
      - .flake8
      - .gitignore
      - .isort.cfg
      - .shellcheckrc
      - '*.md'
      - benchmarks/
      - misc/
      - solutions/
      - templates/
      - tsconfig.json
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: make test
